import type { CodeLine } from "./concept-projects";

const L = (
  number: number,
  tokens: CodeLine["tokens"],
): CodeLine => ({ number, tokens });

export const bellaVistaCode: { filename: string; lines: CodeLine[] }[] = [
  {
    filename: "app/bella-vista/page.tsx",
    lines: [
      L(1, [{ text: '"use client";', type: "string" }]),
      L(2, [
        { text: "import", type: "keyword" },
        { text: " { useState } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "react";', type: "string" },
      ]),
      L(3, [
        { text: "import", type: "keyword" },
        { text: " Image ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "next/image";', type: "string" },
      ]),
      L(4, [
        { text: "import", type: "keyword" },
        { text: " { motion } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "framer-motion";', type: "string" },
      ]),
      L(5, [
        { text: "import", type: "keyword" },
        { text: " { images } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "@/lib/images";', type: "string" },
      ]),
      L(6, []),
      L(7, [
        { text: "const", type: "keyword" },
        { text: " NAV = [", type: "plain" },
      ]),
      L(8, [{ text: '  { id: "accueil", label: "Accueil" },', type: "string" }]),
      L(9, [{ text: '  { id: "menu", label: "Menu" },', type: "string" }]),
      L(10, [{ text: '  { id: "chef", label: "Le Chef" },', type: "string" }]),
      L(11, [{ text: '  { id: "galerie", label: "Galerie" },', type: "string" }]),
      L(12, [{ text: '  { id: "reservation", label: "Réservation" },', type: "string" }]),
      L(13, [{ text: "];", type: "plain" }]),
      L(14, []),
      L(15, [
        { text: "const", type: "keyword" },
        { text: " MENU = [", type: "plain" },
      ]),
      L(16, [
        {
          text: '  { name: "Burratina", price: "18€", desc: "Tomates confites, basilic" },',
          type: "string",
        },
      ]),
      L(17, [
        {
          text: '  { name: "Risotto aux truffes", price: "32€", desc: "Parmesan 24 mois" },',
          type: "string",
        },
      ]),
      L(18, [
        {
          text: '  { name: "Tiramisu maison", price: "12€", desc: "Mascarpone, espresso" },',
          type: "string",
        },
      ]),
      L(19, [{ text: "];", type: "plain" }]),
      L(20, []),
      L(21, [
        { text: "export default function", type: "keyword" },
        { text: " BellaVistaPage", type: "function" },
        { text: "() {", type: "plain" },
      ]),
      L(22, [
        { text: "  const", type: "keyword" },
        { text: " [formState, setFormState] = useState<", type: "plain" },
        { text: '"idle" | "loading" | "success"', type: "string" },
        { text: ">(", type: "plain" },
        { text: '"idle"', type: "string" },
        { text: ");", type: "plain" },
      ]),
      L(23, [
        { text: "  const", type: "keyword" },
        { text: " scrollToId = (id: ", type: "plain" },
        { text: "string", type: "type" },
        { text: ") => document.getElementById(id)?.scrollIntoView({ behavior: ", type: "plain" },
        { text: '"smooth"', type: "string" },
        { text: " });", type: "plain" },
      ]),
      L(24, []),
      L(25, [
        { text: "  async function", type: "keyword" },
        { text: " handleReservation", type: "function" },
        { text: "(e: React.FormEvent) {", type: "plain" },
      ]),
      L(26, [{ text: "    e.preventDefault();", type: "plain" }]),
      L(27, [{ text: '    setFormState("loading");', type: "plain" }]),
      L(28, [{ text: "    await new Promise((r) => setTimeout(r, 900));", type: "plain" }]),
      L(29, [{ text: '    setFormState("success");', type: "plain" }]),
      L(30, [{ text: "  }", type: "plain" }]),
      L(31, []),
      L(32, [{ text: "  return (", type: "plain" }]),
      L(33, [
        { text: "    <", type: "plain" },
        { text: "main", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"bella-vista-root"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(34, [
        { text: "      <", type: "plain" },
        { text: "header", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"sticky top-0 z-50 bella-nav"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(35, [
        { text: "        {NAV.map((item) => (", type: "plain" },
      ]),
      L(36, [
        { text: "          <", type: "plain" },
        { text: "button", type: "tag" },
        { text: " key={item.id} onClick={() => scrollToId(item.id)}>", type: "attr" },
      ]),
      L(37, [{ text: "            {item.label}", type: "plain" }]),
      L(38, [
        { text: "          </", type: "plain" },
        { text: "button", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(39, [{ text: "        ))}", type: "plain" }]),
      L(40, [
        { text: "      </", type: "plain" },
        { text: "header", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(41, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " id=", type: "attr" },
        { text: '"accueil"', type: "string" },
        { text: " className=", type: "attr" },
        { text: '"relative min-h-screen"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(42, [
        { text: "        <", type: "plain" },
        { text: "Image", type: "tag" },
        { text: " src={images.bellaVista.hero} fill priority className=", type: "attr" },
        { text: '"object-cover"', type: "string" },
        { text: " />", type: "plain" },
      ]),
      L(43, [
        { text: "        <", type: "plain" },
        { text: "div", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"absolute inset-0 bg-black/55"', type: "string" },
        { text: " />", type: "plain" },
      ]),
      L(44, [
        { text: "        <", type: "plain" },
        { text: "motion.h1", type: "tag" },
        { text: " initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}>", type: "attr" },
      ]),
      L(45, [{ text: "          Bella Vista", type: "string" }]),
      L(46, [
        { text: "        </", type: "plain" },
        { text: "motion.h1", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(47, [
        { text: "        <", type: "plain" },
        { text: "button", type: "tag" },
        { text: " onClick={() => scrollToId(", type: "attr" },
        { text: '"reservation"', type: "string" },
        { text: ")} className=", type: "plain" },
        { text: '"bella-btn"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(48, [{ text: "          Réserver une table", type: "string" }]),
      L(49, [
        { text: "        </", type: "plain" },
        { text: "button", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(50, [
        { text: "      </", type: "plain" },
        { text: "section", type: "tag" },
        { text: ">", type: "plain" },
      ]),
    ],
  },
];

export const titanFitnessCode: { filename: string; lines: CodeLine[] }[] = [
  {
    filename: "app/titan-fitness/page.tsx",
    lines: [
      L(1, [{ text: '"use client";', type: "string" }]),
      L(2, [
        { text: "import", type: "keyword" },
        { text: " { useMemo, useState } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "react";', type: "string" },
      ]),
      L(3, [
        { text: "import", type: "keyword" },
        { text: " { motion } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "framer-motion";', type: "string" },
      ]),
      L(4, []),
      L(5, [
        { text: "function", type: "keyword" },
        { text: " calculateBmi", type: "function" },
        { text: "(heightCm: ", type: "plain" },
        { text: "number", type: "type" },
        { text: ", weightKg: ", type: "plain" },
        { text: "number", type: "type" },
        { text: ") {", type: "plain" },
      ]),
      L(6, [
        { text: "  const", type: "keyword" },
        { text: " heightM = heightCm / ", type: "plain" },
        { text: "100", type: "number" },
        { text: ";", type: "plain" },
      ]),
      L(7, [
        { text: "  return", type: "keyword" },
        { text: " weightKg / (heightM * heightM);", type: "plain" },
      ]),
      L(8, [{ text: "}", type: "plain" }]),
      L(9, []),
      L(10, [
        { text: "function", type: "keyword" },
        { text: " bmiCategory", type: "function" },
        { text: "(bmi: ", type: "plain" },
        { text: "number", type: "type" },
        { text: ") {", type: "plain" },
      ]),
      L(11, [
        { text: "  if", type: "keyword" },
        { text: " (bmi < ", type: "plain" },
        { text: "18.5", type: "number" },
        { text: ") ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Insuffisance pondérale";', type: "string" },
      ]),
      L(12, [
        { text: "  if", type: "keyword" },
        { text: " (bmi < ", type: "plain" },
        { text: "25", type: "number" },
        { text: ") ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Poids normal";', type: "string" },
      ]),
      L(13, [
        { text: "  if", type: "keyword" },
        { text: " (bmi < ", type: "plain" },
        { text: "30", type: "number" },
        { text: ") ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Surpoids";', type: "string" },
      ]),
      L(14, [
        { text: "  return", type: "keyword" },
        { text: ' "Obésité";', type: "string" },
      ]),
      L(15, [{ text: "}", type: "plain" }]),
      L(16, []),
      L(17, [
        { text: "const", type: "keyword" },
        { text: " PLANS = [", type: "plain" },
      ]),
      L(18, [
        {
          text: '  { name: "Essentiel", price: 29, features: ["Accès salle", "1 programme"] },',
          type: "string",
        },
      ]),
      L(19, [
        {
          text: '  { name: "Pro", price: 49, highlighted: true, features: ["Coaching", "Nutrition"] },',
          type: "string",
        },
      ]),
      L(20, [
        {
          text: '  { name: "Elite", price: 79, features: ["Accès illimité", "Suivi premium"] },',
          type: "string",
        },
      ]),
      L(21, [{ text: "];", type: "plain" }]),
      L(22, []),
      L(23, [
        { text: "export default function", type: "keyword" },
        { text: " TitanFitnessPage", type: "function" },
        { text: "() {", type: "plain" },
      ]),
      L(24, [
        { text: "  const", type: "keyword" },
        { text: " [height, setHeight] = useState(", type: "plain" },
        { text: "175", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(25, [
        { text: "  const", type: "keyword" },
        { text: " [weight, setWeight] = useState(", type: "plain" },
        { text: "72", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(26, [
        { text: "  const", type: "keyword" },
        { text: " [frequency, setFrequency] = useState(", type: "plain" },
        { text: "3", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(27, []),
      L(28, [
        { text: "  const", type: "keyword" },
        { text: " bmi = useMemo(() => calculateBmi(height, weight), [height, weight]);", type: "plain" },
      ]),
      L(29, [
        { text: "  const", type: "keyword" },
        { text: " category = useMemo(() => bmiCategory(bmi), [bmi]);", type: "plain" },
      ]),
      L(30, [
        { text: "  const", type: "keyword" },
        { text: " estimatedWeeks = Math.max(", type: "plain" },
        { text: "4", type: "number" },
        { text: ", ", type: "plain" },
        { text: "12", type: "number" },
        { text: " - frequency * ", type: "plain" },
        { text: "2", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(31, []),
      L(32, [{ text: "  return (", type: "plain" }]),
      L(33, [
        { text: "    <", type: "plain" },
        { text: "main", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"titan-root bg-[#0a0a0a] text-white"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(34, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"titan-hero px-6 py-24"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(35, [
        { text: "        <", type: "plain" },
        { text: "motion.h1", type: "tag" },
        { text: " initial={{ opacity: 0 }} animate={{ opacity: 1 }}>", type: "attr" },
      ]),
      L(36, [{ text: "          Repoussez vos limites", type: "string" }]),
      L(37, [
        { text: "        </", type: "plain" },
        { text: "motion.h1", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(38, [
        { text: "        <", type: "plain" },
        { text: "p", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"text-zinc-400 max-w-xl"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(39, [
        {
          text: "          Coaching premium, programmes sur mesure et suivi nutritionnel.",
          type: "string",
        },
      ]),
      L(40, [
        { text: "        </", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(41, [
        { text: "      </", type: "plain" },
        { text: "section", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(42, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " id=", type: "attr" },
        { text: '"imc"', type: "string" },
        { text: " className=", type: "attr" },
        { text: '"titan-panel"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(43, [
        { text: "        <", type: "plain" },
        { text: "input", type: "tag" },
        { text: " type=", type: "attr" },
        { text: '"range"', type: "string" },
        { text: " value={height} onChange={(e) => setHeight(+e.target.value)} />", type: "attr" },
      ]),
      L(44, [
        { text: "        <", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
        { text: "IMC : {bmi.toFixed(1)} — {category}", type: "plain" },
        { text: "</", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(45, [
        { text: "      </", type: "plain" },
        { text: "section", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(46, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"grid md:grid-cols-3 gap-4"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(47, [{ text: "        {PLANS.map((plan) => (", type: "plain" }]),
      L(48, [
        { text: "          <", type: "plain" },
        { text: "article", type: "tag" },
        { text: " key={plan.name} className={plan.highlighted ? ", type: "attr" },
        { text: '"titan-plan featured"', type: "string" },
        { text: " : ", type: "plain" },
        { text: '"titan-plan"', type: "string" },
        { text: "}>", type: "plain" },
      ]),
      L(49, [
        { text: "            <", type: "plain" },
        { text: "h3", type: "tag" },
        { text: ">{plan.name}</", type: "attr" },
        { text: "h3", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(50, [
        { text: "            <", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">{plan.price}€/mois</", type: "attr" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
      ]),
    ],
  },
];

export const novaHabitatCode: { filename: string; lines: CodeLine[] }[] = [
  {
    filename: "app/nova-habitat/page.tsx",
    lines: [
      L(1, [{ text: '"use client";', type: "string" }]),
      L(2, [
        { text: "import", type: "keyword" },
        { text: " { useMemo, useState } ", type: "plain" },
        { text: "from", type: "keyword" },
        { text: ' "react";', type: "string" },
      ]),
      L(3, []),
      L(4, [
        { text: "type", type: "keyword" },
        { text: " ProjectType = ", type: "plain" },
        { text: '"cuisine" | "sdb" | "complet" | "extension"', type: "string" },
        { text: ";", type: "plain" },
      ]),
      L(5, []),
      L(6, [
        { text: "function", type: "keyword" },
        { text: " estimateProject", type: "function" },
        { text: "(type: ProjectType, surface: ", type: "plain" },
        { text: "number", type: "type" },
        { text: ", finish: ", type: "plain" },
        { text: "number", type: "type" },
        { text: ") {", type: "plain" },
      ]),
      L(7, [
        { text: "  const", type: "keyword" },
        { text: " rates: Record<ProjectType, ", type: "plain" },
        { text: "number", type: "type" },
        { text: "> = {", type: "plain" },
      ]),
      L(8, [
        { text: "    cuisine: ", type: "plain" },
        { text: "850", type: "number" },
        { text: ", sdb: ", type: "plain" },
        { text: "950", type: "number" },
        { text: ", complet: ", type: "plain" },
        { text: "1200", type: "number" },
        { text: ", extension: ", type: "plain" },
        { text: "780", type: "number" },
        { text: ", ", type: "plain" },
      ]),
      L(9, [{ text: "  };", type: "plain" }]),
      L(10, [
        { text: "  const", type: "keyword" },
        { text: " base = rates[type] * surface * finish;", type: "plain" },
      ]),
      L(11, [
        { text: "  return", type: "keyword" },
        { text: " { min: Math.round(base * ", type: "plain" },
        { text: "0.9", type: "number" },
        { text: "), max: Math.round(base * ", type: "plain" },
        { text: "1.15", type: "number" },
        { text: ") };", type: "plain" },
      ]),
      L(12, [{ text: "}", type: "plain" }]),
      L(13, []),
      L(14, [
        { text: "function", type: "keyword" },
        { text: " botReply", type: "function" },
        { text: "(input: ", type: "plain" },
        { text: "string", type: "type" },
        { text: ") {", type: "plain" },
      ]),
      L(15, [
        { text: "  const", type: "keyword" },
        { text: " msg = input.toLowerCase();", type: "plain" },
      ]),
      L(16, [
        { text: "  if", type: "keyword" },
        { text: " (msg.includes(", type: "plain" },
        { text: '"devis"', type: "string" },
        { text: ")) ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Remplissez le formulaire devis pour une estimation.";', type: "string" },
      ]),
      L(17, [
        { text: "  if", type: "keyword" },
        { text: " (msg.includes(", type: "plain" },
        { text: '"délai"', type: "string" },
        { text: ") || msg.includes(", type: "plain" },
        { text: '"delai"', type: "string" },
        { text: ")) ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Comptez 4 à 8 semaines selon le projet.";', type: "string" },
      ]),
      L(18, [
        { text: "  if", type: "keyword" },
        { text: " (msg.includes(", type: "plain" },
        { text: '"prix"', type: "string" },
        { text: ") || msg.includes(", type: "plain" },
        { text: '"budget"', type: "string" },
        { text: ")) ", type: "plain" },
        { text: "return", type: "keyword" },
        { text: ' "Utilisez le calculateur pour une fourchette indicative.";', type: "string" },
      ]),
      L(19, [
        { text: "  return", type: "keyword" },
        { text: ' "Posez une question sur devis, délais ou budget.";', type: "string" },
      ]),
      L(20, [{ text: "}", type: "plain" }]),
      L(21, []),
      L(22, [
        { text: "export default function", type: "keyword" },
        { text: " NovaHabitatPage", type: "function" },
        { text: "() {", type: "plain" },
      ]),
      L(23, [
        { text: "  const", type: "keyword" },
        { text: " [projectType, setProjectType] = useState<ProjectType>(", type: "plain" },
        { text: '"cuisine"', type: "string" },
        { text: ");", type: "plain" },
      ]),
      L(24, [
        { text: "  const", type: "keyword" },
        { text: " [surface, setSurface] = useState(", type: "plain" },
        { text: "35", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(25, [
        { text: "  const", type: "keyword" },
        { text: " [finish, setFinish] = useState(", type: "plain" },
        { text: "1", type: "number" },
        { text: ");", type: "plain" },
      ]),
      L(26, [
        { text: "  const", type: "keyword" },
        { text: " estimate = useMemo(", type: "plain" },
      ]),
      L(27, [
        { text: "    () => estimateProject(projectType, surface, finish),", type: "plain" },
      ]),
      L(28, [
        { text: "    [projectType, surface, finish],", type: "plain" },
      ]),
      L(29, [{ text: "  );", type: "plain" }]),
      L(30, []),
      L(31, [{ text: "  return (", type: "plain" }]),
      L(32, [
        { text: "    <", type: "plain" },
        { text: "main", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"nova-root"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(33, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " className=", type: "attr" },
        { text: '"nova-hero"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(34, [{ text: "        <h1>Rénovation clés en main</h1>", type: "plain" }]),
      L(35, [
        { text: "        <", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
        { text: "Devis gratuit · Paris & Île-de-France", type: "string" },
        { text: "</", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(36, [
        { text: "      </", type: "plain" },
        { text: "section", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(37, [
        { text: "      <", type: "plain" },
        { text: "section", type: "tag" },
        { text: " id=", type: "attr" },
        { text: '"estimateur"', type: "string" },
        { text: " className=", type: "attr" },
        { text: '"nova-panel"', type: "string" },
        { text: ">", type: "plain" },
      ]),
      L(38, [
        { text: "        <", type: "plain" },
        { text: "select", type: "tag" },
        { text: " value={projectType} onChange={(e) => setProjectType(e.target.value)}>", type: "attr" },
      ]),
      L(39, [{ text: '          <option value="cuisine">Cuisine</option>', type: "string" }]),
      L(40, [{ text: '          <option value="sdb">Salle de bain</option>', type: "string" }]),
      L(41, [
        { text: "        </", type: "plain" },
        { text: "select", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(42, [
        { text: "        <", type: "plain" },
        { text: "input", type: "tag" },
        { text: " type=", type: "attr" },
        { text: '"range"', type: "string" },
        { text: " min=", type: "attr" },
        { text: '"10"', type: "string" },
        { text: " max=", type: "attr" },
        { text: '"120"', type: "string" },
        { text: " value={surface} onChange={(e) => setSurface(+e.target.value)} />", type: "attr" },
      ]),
      L(43, [
        { text: "        <", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
        { text: "Estimation : {estimate.min}€ – {estimate.max}€", type: "plain" },
        { text: "</", type: "plain" },
        { text: "p", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(44, [
        { text: "      </", type: "plain" },
        { text: "section", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(45, [
        { text: "      <", type: "plain" },
        { text: "AiChatbot", type: "tag" },
        { text: " replyFn={botReply} />", type: "attr" },
      ]),
      L(46, [
        { text: "    </", type: "plain" },
        { text: "main", type: "tag" },
        { text: ">", type: "plain" },
      ]),
      L(47, [{ text: "  );", type: "plain" }]),
      L(48, [{ text: "}", type: "plain" }]),
    ],
  },
];
